name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs At 12:00 AM, only on Friday
    - cron: "0 0 * * FRI"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCSdK76iChD7P1ZqrmkW4Odw
          comment_tag_name: YOUTUBE-CARDS
          card_width: 250
          border_radius: 5
          background_color: "#0d1117"
          title_color: "#ffffff"
          readme_path: README.md
      - run: echo OUTPUT '${{ steps.youtube-cards.outputs.markdown }}'
        shell: bash